# Generated by Django 6.0.4 on 2026-04-28 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('password_cifrada', models.CharField(max_length=255)),
                ('token_sesion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('alias', models.CharField(default='Cuenta Clara', max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='api.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(editable=False, max_length=7, unique=True)),
                ('entidad_origen', models.CharField(max_length=100)),
                ('iban_origen', models.CharField(max_length=34)),
                ('iban_destino', models.CharField(max_length=34)),
                ('pet_cancelar_ordenes', models.BooleanField(default=False)),
                ('pet_bloquear_entrantes', models.BooleanField(default=False)),
                ('pet_transferir_saldo_cierre', models.BooleanField(default=False)),
                ('pet_recibir_info', models.BooleanField(default=False)),
                ('act_habilitar_ordenes', models.BooleanField(default=False)),
                ('act_aceptar_adeudos', models.BooleanField(default=False)),
                ('act_informar_emisores', models.BooleanField(default=False)),
                ('fecha_ejecucion', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Traslado completado'), ('RECHAZADO', 'Solicitud rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='traslados_pdfs/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='api.cuenta')),
            ],
        ),
    ]
