# Generated by Django 6.0.4 on 2026-05-06 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tarjeta'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='pan',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
