# Generated by Django 6.0.4 on 2026-05-20 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movimiento_tarjeta_alter_tarjeta_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cuenta'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tarjeta'),
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cuenta__isnull', False), ('tarjeta__isnull', True)), models.Q(('cuenta__isnull', True), ('tarjeta__isnull', False)), _connector='OR'), name='check_movimiento'),
        ),
    ]
